### ISSUE TITLE
Сместить кнопку или уменьшить блок с названием

### ISSUE THREAD

**Issue by simgislab** [nextgis/rgada_toponyms#1]
... а то он налезает на кнопку и блокирует ее

![](http://m-d.me/img/ss/20180106-zaZ1o8t0.png)

**Comment by lisovenkoNastya** [comment]
Я могу уменьшить блок с названием. Это не проблема.
Но, может быть, все-таки сделать заголовок карты более читабельным?

Варианты заголовка:
1. Геоуказатель к монографии A.A. Фролова «Новгородские писцовые книги: источники и методы исследования» - (это если необходимо сохранить упоминание полного названия и автора. Прочая дополнительная информация есть в панели "О проекте")
2. Геообъекты Новгородских писцовых книг - вот так, конечно, мне нравится больше.

Какой вариант подходит? или, может быть, есть третий вариант?

**Comment by simgislab** [comment]
тоже поддерживаю сокращение и вынос полного правильного цитирования в описание проекта

**Comment by npkfrolov** [comment]
Соглашусь с вариантом 1, предложенным Настей. Вариант два - это искажение содержания, неоправданное расширение объекта описания.

**Comment by lisovenkoNastya** [comment]
Поправила - http://nextgis.ru/demo/rgada/rgada_toponyms/
