### ISSUE TITLE
данные из поля group

### ISSUE THREAD

**Issue by npkfrolov** [nextgis/rgada_toponyms#2]
Еще нужно, чтобы в правой, табличной, части веб-страницы отображались данные из поля group. Мне кажется, лучше всего, чтобы это была отдельная колонка, крайняя слева, шрифтом размера того же, что и данные о страницах или даже мельче на кегль-два. Смысл в том, чтобы пользователь мог понять, что четыре категории названий выделены в отдельные группы и расположены внутри них по алфавиту. В частности, на букву М в общем указателе встречается "монастыри", а у же внутри этой группы, снова с буквы А, приведены названия монастырей. Когда список монастырей исчерпан, идет снова основной список указателя.

**Comment by simgislab** [comment]
т.е. в этой колонке должно быть написано: "основной указатель" или "монастыри" ?

про четыре категории названий не очень понятно

**Comment by npkfrolov** [comment]
Либо “основной указатель”, либо “монастыри”, либо три других варианта, да.

**Comment by lisovenkoNastya** [comment]
https://image.prntscr.com/image/_KFhaMZzTBy_C4YI_Rg70Q.png
Предлагаю такой вариант внешнего вида.
Первым столбцом группу делать не хочется, так как в этом случае смещается акцент с заголовка.
Подходит такой вариант?

И два сопутствующих вопроса:
1. Нужна ли правая цифра - поле ogc_fid
2. Правильно ли, что сейчас объекты сортируются по ogc_fid?

**Comment by npkfrolov** [comment]
Спасибо.
Внешний вид меня устраивает. Правая цифра нужна - она показывает место названия во всем указателе. Соответственно, можно судить, какие из названий не локализованы. Но сортировать лучше не по ogс_fid, а по order_number. Сейчас они совпадают по значению, но со временем я добавлю еще кое-какие названия, и у них order_number останется таким, каким и должен быть, а ogс_fid пойдет уже другим. 
АФ

**Comment by lisovenkoNastya** [comment]
Готово - http://nextgis.ru/demo/rgada/rgada_toponyms/
вынесла вперед столбец с ogc_fid
Добавила возможность поиска по названию группы.

https://github.com/nextgis/rgada_toponyms/commit/c983d9669f977ac55e8b923e05a392b25ce2220f
